import React from 'react';

const SkillSection = () => {
  return (
    <section className="myskill" id="myskill">
      <div className="container">
        <h1 className="sub-title">My <span>Skill</span></h1>
        <div className="service-list">
          <div>
            <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACQAAAAkCAYAAADhAJiYAAAAAXNSR0IArs4c6QAAAfJJREFUWEftl91xwjAQhPfoAGiAVAJUklBJoBJMJSGVxA0AHUSZQ2Dr5NPvmAkP+NFG0qe9vZUgPNlDT8aDF1CqIuMqdDEf+MUSExwAtJhSmwLwv48LdDZfAFbXRQhrTOn430CmA5hR1WarBqm7vpgFDH5u31rM6K1UHSvsWM/JbEH4vE5n0GBOm5qpHwW0w5y2jwfisoQ652x6//iGjo3zqPMV4g4y+FZ3Lv0DuIY+mT0ICxA2OTGQBrKL7bt2NhiW42JWMOCW56c3NOeSHWvfW+Wi2RQHkgvZaTUgaege2H1/L41Vqgn5KwykT6aHXSwQrUrcfYsOgjc1QaOppQO5C/Ry88705HUNrQWiVZpL10MBR81XEsj3i4U5YkbrYAuXBKK+UeErCeTuNOQXn6w0EIdWEBv2gTj6s2rdcYUMHZJ0CCSOGa1k3L7JWnfrxQLRh8rwZomphxkSC0QXpsCbpW0vMyQUiBLGDc1wlt3GpIJRz5D7wZnyj0xqu2Ti4pZzdMgMcZM2dUOUBuajI5xlWQq50tvDtRX3nFQg8ngLtYxmmbNOWqFQ+5YEYjBVhx/qgUoDMRNqLKDqG6LPWQ9UEoiZ6tgmrHlyA7Fi7log/YZYATBOyVgh/odq8A7CIXYDLGWsU6h0lYLfv4BSYj2dQn9TThI0xt6UJQAAAABJRU5ErkJggg==" alt="UI/UX design" />
            <h2>UI/UX design</h2>
            <p>UI/UX (User Interface/User Experience) adalah disiplin desain yang fokus pada menciptakan pengalaman pengguna yang optimal dalam interaksi dengan produk atau layanan digital. UI berkaitan dengan elemen visual dan interaktif, seperti tata letak, warna, dan tombol, yang memungkinkan pengguna berinteraksi dengan antarmuka. UX mencakup perencanaan dan penyesuaian keseluruhan pengalaman, termasuk navigasi yang mudah, konsistensi, dan respon terhadap kebutuhan pengguna. Kualitas UI/UX dapat memengaruhi kepuasan pengguna, retensi, dan kesuksesan produk. Dengan desain yang baik, UI/UX dapat menciptakan pengalaman yang menyenangkan, efisien, dan bermanfaat bagi pengguna, meningkatkan nilai produk digital</p>
          </div>
          <div>
            <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACQAAAAkCAYAAADhAJiYAAAAAXNSR0IArs4c6QAAAjdJREFUWEflV4ttwjAQfccGwACESYBJCpMAkxQmgU5SGICyAa5ejgtOGufjUBqplpCCkuhe3ufOFvRsSc/w4J8AurolhrKLYf93GLq4d4xl1R9AX+6AkSz6AYhy3TDrB0NXl8DhE4IphnL6W4YMjMMWY9nEgOE7zzH11c3hcIDDLpOKAIE5gGMbtroDurgNBGsYMwRywzJlKIKpboAYb8ESglXad4wpwQJDOcbIFg+IaXIgoKeB6eYh9hogwUimKRP6H7H9x9iMZ4gAHE6ZiYsAY/TqlDKV7C1jRAExbX8Ue03TGgPsUwNbHwJOd1+92NSUxEDZILUWYEaPkC3eQ1ZMG2CSY+mlsWev4SrrM/SV3svvhfjOLe3ak7qh24wh676C2d0f9YNTmSO4x7MqKYOgraJkNQWkiaI0NC3jLun1z2X3HD4wwC4HyDr5SIJ1mwHyy9qXF6E02W5w1OiMC+4m2wMi7VVDs0wqTWS+b3WSzE8U55dKZ8v3kxpeZd2nkumiqZMm0789Q/q1GvUyYJFT3r4uFlD0MSeUrnhAlhTKoj8UUkfZmMJtzNmsniHrQYO0uG5HbXvK04Uff0adqxj3Olq8+9WAbDZV9I3Gtewjak60YUA2OLlF1dRwep+hTPnJ8q8tfdwJ2PUke8+2uRXGr5esLFVajIWK63yXTEFb4fzoobeCW5NmgPw+pEcbeAzQM6ccI/TVY4QQHJnNj5GA1u0AhQwT6s6NDfZ48DmAIgqHXukdoG9ASP8lcOFB3AAAAABJRU5ErkJggg=="/>
            <h2>Bahasa Pemrograman Java</h2>
            <p>Java adalah bahasa pemrograman tingkat tinggi yang kuat dan serbaguna. Dikembangkan oleh Sun Microsystems, Java terkenal karena portabilitasnya yang tinggi, memungkinkan program yang ditulis dalam bahasa ini dapat berjalan di berbagai platform tanpa modifikasi. Java digunakan secara luas dalam pengembangan perangkat lunak, terutama untuk aplikasi desktop, perangkat mobile, dan aplikasi web. Keamanan yang kuat juga menjadi ciri khasnya, dengan JVM (Java Virtual Machine) yang menjalankan kode dalam lingkungan terisolasi. Java memiliki beragam library dan framework yang mendukung pengembangan yang efisien, menjadikannya pilihan utama untuk pengembang yang ingin menciptakan aplikasi yang andal dan skalabel.</p>
            </div>
                    <div>
                        <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACQAAAAkCAYAAADhAJiYAAAAAXNSR0IArs4c6QAAAWxJREFUWEftmNGVgjAQRd/YgdqAdoKdYCW6lchWIp1IA0IHzp7JEA0LOeEjRD7Cj+cwkdy8eTMhEFZ20cp4kIFCGRkr1HGBF4rQH6PEN6ixpdp91hjoyVcQLlEmDD2E8YM9XTOQV6isUPZQSIFQPHsoKxRSIBRfyEONM+9hgsHuVeP9cREgRoU9nQ1Iyw8AFqoG4YwtKXDHB7xQDvbJhEA1dnSazNiTbyCUJpYMSJWpetXuRjXC6XsKWSBJE0PSOH0lU8j1lXrn8k6Ti5YMCGh6Q3/eBr9satGhAeMXG1TvSpO77htpQoXcxAzB1Fc3AEXMKpPeov3G14fkvi1vxfu0gpal8iIBicySBrtKKWd7cmiZzcS2IfrSYxtohJSJWQXA3S50/R2XPaR/jI4TZUShaI2xwY6Og8bi+kID6pt/R5wBTEQgO6GWNBkv+Q6WVkn5TbS5etvwjMAsD63uKD1jYUsOyZ9jQuquTqE/IwkhNHBK6mkAAAAASUVORK5CYII="/>
                        <h2>JavaScript</h2>
                        <p>bahasa pemrograman tingkat tinggi yang digunakan secara luas dalam pengembangan web. Berbeda dengan bahasa pemrograman server-side seperti Java, JavaScript berjalan di sisi klien (browser) dan memberikan interaktivitas pada situs web. Ini memungkinkan pembuatan aplikasi web yang responsif, seperti permainan online, formulir interaktif, dan tampilan dinamis. JavaScript mendukung banyak framework dan library, seperti React, Angular, dan Vue, yang mempermudah pengembangan web yang kompleks. Selain itu, Node.js memungkinkan penggunaan JavaScript di sisi server, yang menghasilkan stack pengembangan lengkap (full-stack) yang serbaguna. JavaScript adalah komponen utama dalam ekosistem web modern dan terus berkembang pesat.</p>
                    </div>
                    <div>
                        <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACQAAAAkCAYAAADhAJiYAAAAAXNSR0IArs4c6QAAAepJREFUWEftl9F5wjAMhE9sAAzQMAkwSWGS0kmASZpO0iwAbID4RL6A7diWbdKWB/KaxP59ku9swpM99GQ8eAFpFQkrdOIVzqi0AYrej9BgTDvfv2GgI38BWBRNqP3E2GFK6zygA29BWGljF70vBNqA8FE0ofYT4xNT2uQq9HtAhHV+D0lTM7bGKmowvrXFe98T3gFjgxQCLcCQxu6eGhNaFgG5/UhYYkx1XslOXIHxMwiQu2MJM4ypeRSowYRmt0Fk1amPu1uLgGSyI7Mx5x2or14qWvvdhIL+F8+yI0vJ7m5tDmTD/hmQ7dam1DnRYvuZXXpnKZpCLlBwdwQlOnHWbo0DZWzXCJDtZ5HYkDE0INet08xxhPrmM67BDgyU1rxmVh3YXlQkx3SFYqtzJzJRzWjolz2YYylA4YbsZ90d6Z+AKpyxAmFuHOQaMPbW0SIjNlIUcvPM7yHi3IFsgmuukdgoA2rL4U3qXsf7IiYSGzpQP8+6OaU0NUbX85Ec2FtAAZAyAm/B4+8AQHae+Te+HCVSbijR2EhVaMjbh3rI02+uQ94+FJdOU6jrDbmjnTHPvBq1NiBP4JbhdoCukK9nuua1Pchs+D3MPEsLnOtXZUDmBALXqlelqhDjexwoY/Upn76ANJWeTqELn+3rJZR5XhQAAAAASUVORK5CYII="/>
                        <h2>HTML</h2>
                        <p>HTML (Hypertext Markup Language) adalah bahasa markup yang digunakan untuk membuat struktur konten di web. Ini adalah fondasi dari setiap halaman web. HTML menggunakan tag (elemen) untuk mendefinisikan berbagai elemen dalam halaman seperti teks, gambar, tautan, tabel, dan formulir. Dengan tag ini, pengembang web dapat mengorganisir informasi dengan baik, menciptakan hierarki, dan menentukan bagaimana konten ditampilkan di browser pengguna. HTML bekerja sama dengan bahasa pemrograman lain seperti CSS (Cascading Style Sheets) dan JavaScript untuk menghasilkan halaman web yang interaktif dan menarik. HTML terus berkembang dengan versi terbaru dan standar web yang lebih modern.</p>
                    </div>
                    <div>
                        <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACQAAAAkCAYAAADhAJiYAAAAAXNSR0IArs4c6QAAAd1JREFUWEftmP1xwjAMxZ/YAFgAJgE2gUmASYBJyiZlAWAD1HN9IbZqS3YgLXfFd/yXRD8/fTwbwostejEevIGsjOQVuvIEgPv1s4Z0TH04D3TmHQjLXmgYe4xpVQu0AWH9X4C2GNOmTqErL8HY9aIQYYUh7WuB5mB8BC+dwEgWoglNmEcN8iSgI0a0MIOnHriw25iD8oswxZBOtQpNwPgMXnoEyH2nHSGdgBzJhVmk7FCsUFi0F46BRpQdN7p1yA8V04i0xBsD/gQoDCqVHtE0tzdLobgY46/oXddM4ivLblVrsTsQIzvcIm45zxTb8A2orTNr9lHWdb8I5FKW7roBjmjcXG7KUFZXqKt9hGmRpwZlStspkwUZB8qnMwzaKxDQ1o2mXgj00zYW93Qm6tdKWd4+3InyhjXo2xIan/J1NcD+7lVyuCq2UZIyCXRCaqj54y6ShllhGzZQzs/CLsqNDQ/phmJ8plJsoxQoNsYWwE/qAQ73mvBpXIIwi44b4TuKbZQCafbRhHJnm5IbijlM7Yui7JIax5fPGrZRppBuH3V4TwFyIZsCvWFWeVdr7SVzy5A7slOW0kAv3mYWtX5WoWM3oDBAq94kd9eq4Hn/+2GK9XjKzBB1D7wc0BfP6e8l2wMIsAAAAABJRU5ErkJggg=="/>
                        <h2>CSS </h2>
                        <p>CSS (Cascading Style Sheets) adalah bahasa yang digunakan untuk mengatur tampilan dan gaya elemen HTML di halaman web. Dengan CSS, pengembang dapat mengontrol warna, tata letak, ukuran teks, dan efek visual lainnya. Ini memisahkan presentasi (tampilan) dari struktur (konten) dalam desain web, memungkinkan konsistensi dan fleksibilitas yang tinggi. CSS mendukung selektor yang memungkinkan elemen tertentu di-styling, serta cascading nature yang memungkinkan aturan gaya diterapkan secara berlapis dan disisipkan melalui file eksternal. Ini memudahkan pemeliharaan dan perubahan desain situs web secara efisien. CSS berperan kunci dalam menciptakan tampilan profesional dan menarik untuk situs web modern.</p>
                    </div>
        </div>
      </div>
    </section>
  );
}

export default SkillSection;
